name: pangeo
channels:
 - conda-forge
dependencies:
 - esmpy
 - xesmf
 - pangeo-notebook
 - bokeh=2.0
 - cartopy>=0.18 
 - cmip6_preprocessing
 - datashader>=0.11
 - fsspec
 - gcsfs 
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - ipywidgets
 - jupyter-panel-proxy
 - lz4
 - matplotlib
 - nbserverproxy
 - nodejs
 - nomkl
 - numcodecs
 - numpy
 - panel
 - python-blosc
 - scipy
 - tiledb-py
 - xarray
# additional packages on top of pangeo notebook
 - zarr
 - eofs
 - xhistogram
 - xrft
 - xgcm
 - cmip6_preprocessing
 - seaborn
 - nc-time-axis
 - gsw
 - pip
 - pip:
   - git+https://github.com/JiaweiZhuang/xESMF.git
   - git+https://github.com/intake/filesystem_spec.git
   - seawater
   - cmocean

